### PR TITLE
The great refactor

### PR DESCRIPTION
**Pull request by claudiodsf**
I just completed a big code refactoring, thanks to [sourcery.ai](https://sourcery.ai).

Notable changes:

- Use [f-strings](https://realpython.com/python-f-strings/) throughout the code
- Use of [raise from](https://stackoverflow.com/questions/24752395/python-raise-from-usage) construct
- Split complex functions into smaller ones (with some exception remaining...)

Verified on all my test cases: the output should be the same as before.

Calling once more @krisvanneste before merging this PR, to check for potential side effects... thanks!

### CODE REVIEW

**Comment by krisvanneste** [comment]
Claudio,
I will test today or tomorrow, if that's OK with you.

**Comment by claudiodsf** [comment]
> I will test today or tomorrow, if that's OK with you.

Sure! Whenever you have time 😉

**Comment by krisvanneste** [comment]
Claudio,

I ran a quick test, and I obtain exactly the same result as before, both with restitution in sourcespec and with pre-restituted traces.

**Comment by claudiodsf** [comment]
Hi Kris, thank you very much for your test. I'll merge this PR later today.

I have some other small improvements to merge (no testing required :wink:), then I'll release v1.7.

For the next version (tentatively, v2.0), I would like to reorganize the files in subdirectories and improve the Python API. I would also like to have one single executable (`sourcespec`) with subcommands (e.g., `sourcespec invert`, `sourcespec residuals`, `sourcespec plotpars`).
There is also some work ongoing on spectral ratios, which hopefully will be finished.

More importantly, I would like to write the long-overdue paper on SourceSpec and I would like you to be part of it!
Please let me know if that works for you: it would be nice to show some examples of your historical seismograms.

**Comment by krisvanneste** [comment]
Claudio,

Great! I'm happy to be part of this and will try to help where I can.
Before you release a new version, I would like to file an issue that pops up when generating the HTML file.

**Comment by claudiodsf** [comment]
> Great! I'm happy to be part of this and will try to help where I can. 

Cool!

> Before you release a new version, I would like to file an issue that pops up when generating the HTML file.

Sure, go ahead!

**Comment by krisvanneste** [comment]
See https://github.com/SeismicSource/sourcespec/issues/29

**Pull request merged**
