### PR TITLE
V2 asdf

### PR DESCRIPTION
**Pull request by krisvanneste**
In this branch, I add further support to read traces and station inventories from ASDF files:
- Added new `parse_asdf_inventory()` function in `input.station_metadata.py`
- Added new `parse_asdf_traces()` function in `input.traces.py`

These functions can be used interactively as follows:
```
from sourcespec2.input.station_metadata import parse_asdf_inventory
inventory = parse_asdf_inventory(asdf_file)

from sourcespec2.input.traces import parse_asdf_traces
tag = 'raw'
st = parse_asdf_traces(asdf_file, tag, read_headers=True)
```

In addition, I also modified `input.event_parsers.quakeml.parse_qml_file()`, `input.station_metadata.read_station_metadata()` and `input.traces._read_trace_files()` to choose between the ASDF/non-ASDF parsers depending on file extension (`.asdf` or `.h5` for ASDF format). This should allow using ASDF file(s) in the CLI as well, as shown here interactively:
```
from sourcespec2.input import read_event_and_picks
config.options.qml_file = asdf_file
event, picks = read_event_and_picks()

from sourcespec2.input import read_station_metadata
config.station_metadata = asdf_file
inventory = read_station_metadata()

from sourcespec2.input.traces import read_traces
config.options.trace_path = [asdf_file]
st = read_traces()
```

However, as ASDF files may contain different waveform data labeled with tags, we might consider 1 or 2 additional configuration options: `asdf_tag` to specify the tag (the current default is 'raw') and perhaps also `asdf_read_headers` to specify whether or not to try reading trace headers (current default False). The latter is not specifically defined in the ASDF standard, but I implemented the way this is done in ESM as well as my own way (which is more logical).

### CODE REVIEW

**Comment by claudiodsf** [comment]
Hi Kris, I just force-pushed some commits.

Here's what I did:

- I prefer a different approach for reading ASDF file from command line
- I reduced the nesting in `parse_asdf_traces()`: could you please check that the code still works?

More commits to come...

**Comment by krisvanneste** [comment]
Claudio,
Everything still works on my side after replacing `config.options.qml_file` with `config.options.asdf_file`.
Apparently, this new option only relates to event information, while for station metadata and traces the parsing still depends on file extension. Concerning this extension, I included both `.asdf` and `.h5`, but if you would like to come up with a custom HDF5 format for (processed) traces, you may want to restrict this to `.asdf`.

Concerning the use of waveform tags in ASDF files, we should either define a configuration parameter for this or else set the default value of 'tag' in `input.traces.parse-asdf_traces()` to an empty string or `None`, so that the first tag available is used. It is then up to the user to create ASDF files with just 1 tag.

Finally, I noticed that you hardcoded the tag "raw" in `input.traces._parse_asdf_trace_headers()`. I would prefer to add a `tag` argument in this function, otherwise it will break if `parse_asdf_traces()` is called with a different tag value.

**Comment by claudiodsf** [comment]
> Claudio, Everything still works on my side after replacing `config.options.qml_file` with `config.options.asdf_file`. Apparently, this new option only relates to event information, while for station metadata and traces the parsing still depends on file extension.

This is in the next commit to come 😉 

> Concerning this extension, I included both `.asdf` and `.h5`, but if you would like to come up with a custom HDF5 format for (processed) traces, you may want to restrict this to `.asdf`.

I'm thinking about a more robust way to detect the file, not based on the extension...

> Concerning the use of waveform tags in ASDF files, we should either define a configuration parameter for this or else set the default value of 'tag' in `input.traces.parse-asdf_traces()` to an empty string or `None`, so that the first tag available is used. It is then up to the user to create ASDF files with just 1 tag.

Ok, I'm changing the default to `None` for the moment

> Finally, I noticed that you hardcoded the tag "raw" in `input.traces._parse_asdf_trace_headers()`. I would prefer to add a `tag` argument in this function, otherwise it will break if `parse_asdf_traces()` is called with a different tag value.

Oops, that's an error made by Copilot in the refactoring process 😆

**Comment by claudiodsf** [comment]
> > Concerning the use of waveform tags in ASDF files, we should either define a configuration parameter for this or else set the default value of 'tag' in `input.traces.parse-asdf_traces()` to an empty string or `None`, so that the first tag available is used. It is then up to the user to create ASDF files with just 1 tag.
> 
> Ok, I'm changing the default to `None` for the moment
> 
> > Finally, I noticed that you hardcoded the tag "raw" in `input.traces._parse_asdf_trace_headers()`. I would prefer to add a `tag` argument in this function, otherwise it will break if `parse_asdf_traces()` is called with a different tag value.
> 
> Oops, that's an error made by Copilot in the refactoring process 😆

Force-pushed to fix these two points. Is it ok now?

**Comment by claudiodsf** [comment]
Sorry, there was a small error. Force-pushed again

**Comment by krisvanneste** [comment]
Claudio, it works.
If I use `input.traces.read_traces`, the trace headers are not read (because the default value of `read_headers` is False).
If I use `input.traces.parse_asdf_traces`, then trace headers are read correctly, both using `tag='raw'` and `tag=None`.

**Comment by claudiodsf** [comment]
Hi Kris,
I worked a little bit more on this PR to make it possible the following workflow:

```python
from sourcespec2.setup import config
config.options.asdf_file = ASDF_FILE_PATH
config.options.asdf_tag = 'raw'

from sourcespec2.input import read_event_and_picks
event, picks = read_event_and_picks()

from sourcespec2.input import read_station_metadata
inventory = read_station_metadata()

from sourcespec2.input.traces import read_traces
st = read_traces()
```

Note that no other options need to be specified to `config.options`, since I'm using `getattr(config.options, OPTION_NAME, None)` to retrieve them.

Please let me know if you're satisfied with this workflow.

I'm making some further adjustments to include in the same workflow the possibility of reading event and station metadata from the SAC header.

**Comment by claudiodsf** [comment]
I ha ve a question concerning the function `def parse_asdf_traces()`.

Its current signature is:
```python
def parse_asdf_traces(asdf_file, tag=None, read_headers=False):
    ...
```

Is there any practical case in which `tag` is not `None`, but `read_headers` remains `False`?

**Comment by krisvanneste** [comment]
> I have a question concerning the function `def parse_asdf_traces()`.
> 
> Its current signature is:
> 
> ```python
> def parse_asdf_traces(asdf_file, tag=None, read_headers=False):
>     ...
> ```
> 
> Is there any practical case in which `tag` is not `None`, but `read_headers` remains `False`?

Yes, the 2 options are independent. All waveform data within an ASDF file are stored under a particular tag. The corresponding trace headers are stored in the auxiliary data with the same tag. The `tag` option is required if there is more than 1 waveform tag in the ASDF file; the `read_headers` option controls reading of trace headers, for which no standard is defined in the ASDF specification.

**Comment by claudiodsf** [comment]
> Yes, the 2 options are independent. All waveform data within an ASDF file are stored under a particular tag. The corresponding trace headers are stored in the auxiliary data with the same tag. The `tag` option is required if there is more than 1 waveform tag in the ASDF file; the `read_headers` option controls reading of trace headers, for which no standard is defined in the ASDF specification.

Ok, so nothing to change then 😉 .

We will have to add documentation for all the changes and the new features (tracking this in #58).

**Comment by krisvanneste** [comment]
> Hi Kris, I worked a little bit more on this PR to make it possible the following workflow:
> 
> ```python
> from sourcespec2.setup import config
> config.options.asdf_file = ASDF_FILE_PATH
> config.options.asdf_tag = 'raw'
> 
> from sourcespec2.input import read_event_and_picks
> event, picks = read_event_and_picks()
> 
> from sourcespec2.input import read_station_metadata
> inventory = read_station_metadata()
> 
> from sourcespec2.input.traces import read_traces
> st = read_traces()
> ```
> 
> Note that no other options need to be specified to `config.options`, since I'm using `getattr(config.options, OPTION_NAME, None)` to retrieve them.
> 
> Please let me know if you're satisfied with this workflow.
> 
> I'm making some further adjustments to include in the same workflow the possibility of reading event and station metadata from the SAC header.

Claudio,

Just tested, and I confirm it works.
This workflow is easier, but less flexible than before. I now requires that there is only 1 ASDF file, containing all the waveforms, station inventories and event information. This is indeed the most logical way to collect the data for a sourcespec run and acceptable if we indicate this in the documentation.
I'm wondering what happens if along with `config.options.asdf_file`, also one of `config.options.qml_file`, `config.station_metadata` or `config.options.trace_path` are set? Will these take precedence? I think they should.

**Comment by claudiodsf** [comment]
> This workflow is easier, but less flexible than before. I now requires that there is only 1 ASDF file, containing all the waveforms, station inventories and event information. This is indeed the most logical way to collect the data for a sourcespec run and acceptable if we indicate this in the documentation.

Do you see any scenario in which there might be two or more ASDF files?

> I'm wondering what happens if along with `config.options.asdf_file`, also one of `config.options.qml_file`, `config.station_metadata` or `config.options.trace_path` are set? Will these take precedence? I think they should.

In the current implementation:

- For events, the priority is the following ASDF-->QML-->"hypo_file", as you can see [here](https://github.com/SeismicSource/sourcespec/blob/2c499227181edcf61b1ef75b21862ac322943973/sourcespec2/input/event_and_picks.py#L81);

- For station metadata, there is no priority and the inventories read from (StationXML, RESP, PAZ) files and from ASDF are merged, see [here](https://github.com/SeismicSource/sourcespec/blob/2c499227181edcf61b1ef75b21862ac322943973/sourcespec2/input/station_metadata.py#L86);

- For traces, again, no priority. See [here](https://github.com/SeismicSource/sourcespec/blob/2c499227181edcf61b1ef75b21862ac322943973/sourcespec2/input/traces.py#L168).

What do you think?

**Comment by claudiodsf** [comment]
So, you're suggesting to give precedence to QuakeML or `hypo_file` (e.g., SourceSpec event file) over ASDF, likely for a scenario where you have everyting in the ASDF container, but you decided to use another source for the event info?

In any case, I think we should emit log messages on which event information is taking precedence.

**Comment by krisvanneste** [comment]
> Do you see any scenario in which there might be two or more ASDF files?

There is nothing in ASDF imposing that all data related for a single event should be stored in 1 file. It would also be possible to supply 1 file for each station. In that case, each ASDF file would contain the waveform data, inventory, and phase picks related to 1 station. The former 2 (waveform data and inventory) are probably easy to handle (I'm sure about waveform data as `config.options.trace_path` should actually be a list), but I think phase picks would be more difficult (I must confess that I did not consider this possibility before).

How is it with SAC files? One file containing all station data, one file per station, or both possibilities?

**Comment by krisvanneste** [comment]
> So, you're suggesting to give precedence to QuakeML or `hypo_file` (e.g., SourceSpec event file) over ASDF, likely for a scenario where you have everyting in the ASDF container, but you decided to use another source for the event info?

Indeed, not a very common use case probably, but that way it is always possible to override some piece of information which may or may not be present in the ASDF file.

> In any case, I think we should emit log messages on which event information is taking precedence.

Yes, good idea!

**Comment by krisvanneste** [comment]
> SAC files are one per component!

Ugh!

**Comment by claudiodsf** [comment]
> > In any case, I think we should emit log messages on which event information is taking precedence.
> 
> Yes, good idea!

This is done in the latest commit. I'm now working on SAC traces and multiple ASDF files.

**Comment by claudiodsf** [comment]
Hello again,
with the latest commit, I made reading event and picks from SAC headers the least priority source.

So the order is the following:

- SAC trace headers
- ASDF file
- QML file
- Hypocenter file
- Pick file

**Comment by krisvanneste** [comment]
OK, I just tested and everything still works on my side.
Do you want me to make a test with multiple ASDF files?

**Comment by claudiodsf** [comment]
> Do you want me to make a test with multiple ASDF files?

Please, let me do it: I'm "in the zone" 😉

**Comment by krisvanneste** [comment]
> > Do you want me to make a test with multiple ASDF files?
> 
> Please, let me do it: I'm "in the zone" 😉
> 
> Multiple ASDF files still need to be implemented

OK!

**Comment by claudiodsf** [comment]
Ok, multiple ASDF files should work now.

A possible workflow is the follwing:

```python
from sourcespec2.setup import config
config.options.asdf_path = ASDF_FILE_PATH
config.options.asdf_tag = 'raw'

from sourcespec2.input import read_event_and_picks
event, picks = read_event_and_picks()

from sourcespec2.input import read_station_metadata
inventory = read_station_metadata()

from sourcespec2.input import read_traces
st = read_traces()
```

Note that `config.options.asdf_path` will be automatically converted to a list (warning message issued).

To silence the warning, do:

```python
config.options.asdf_path = [ASDF_FILE_PATH]
```

Of course, more than one path can be provided, e.g.:

```python
config.options.asdf_path = [ASDF_FILE_PATH_1, ASDF_FILE_PATH_2, ASDF_FILE_PATH_3]
```

Let me know 😉

**Comment by claudiodsf** [comment]
Do we need also `config.options.asdf_tag` to be a list?

**Comment by krisvanneste** [comment]
> Ok, multiple ASDF files should work now.
> 
> A possible workflow is the follwing:
> 
> ```python
> from sourcespec2.setup import config
> config.options.asdf_path = ASDF_FILE_PATH
> config.options.asdf_tag = 'raw'
> 
> from sourcespec2.input import read_event_and_picks
> event, picks = read_event_and_picks()
> 
> from sourcespec2.input import read_station_metadata
> inventory = read_station_metadata()
> 
> from sourcespec2.input import read_traces
> st = read_traces()
> ```
> 
> Note that `config.options.asdf_path` will be automatically converted to a list (warning message issued).
> 
> To silence the warning, do:
> 
> ```python
> config.options.asdf_path = [ASDF_FILE_PATH]
> ```
> 
> Of course, more than one path can be provided, e.g.:
> 
> ```python
> config.options.asdf_path = [ASDF_FILE_PATH_1, ASDF_FILE_PATH_2, ASDF_FILE_PATH_3]
> ```
> 
> Let me know 😉

Claudio,

Thanks, I will prepare a test case with 1 ASDF file per station and report back.

**Comment by krisvanneste** [comment]
Claudio,

I created a folder with ASDF files for each station (containing event, picks, inventory and traces), specified `config.options.asdf_path` as a list, and it works flawlessly!
However, when there is only 1 ASDF file, and it is not specified as a list, then every character of the filename is interpreted as a separate file, which of course fails. So the conversion to a list does not work.

**Comment by claudiodsf** [comment]
> I created a folder with ASDF files for each station (containing event, picks, inventory and traces), specified `config.options.asdf_path` as a list, and it works flawlessly!

Great!

> However, when there is only 1 ASDF file, and it is not specified as a list, then every character of the filename is interpreted as a separate file, which of course fails. So the conversion to a list does not work.

That's very strange! It should be handled [here](https://github.com/SeismicSource/sourcespec/blob/a977aa49907a9844ccd961954765cb2a224a2c78/sourcespec2/setup/config.py#L115).
May I ask you to debug this? I'm working on another part of the input submodule, right now.

**Comment by krisvanneste** [comment]
> Do we need also `config.options.asdf_tag` to be a list?

Normally not, but unfortunately I can think of 1 case where it might be necessary: ASDF files downloaded from the ESM database. The problem is that in these files, different tags are used for each component, with long and complex names like e.g. `00_hge_emsc_20160824_0000006_acc_mp`, rather than grouping components under the same tag. If you would run sourcespec with files like that, you would need a list of tags (unless all channels are HGx), 1 for each file. In addition, we would also need to support a wildcard in order to read multiple components from 1 file. I have that in my own code, but I did not include it in the code I contributed to sourcespec. I can look into this if you like.

**Comment by krisvanneste** [comment]
> OK, I will have a look

The problem occurred because I override `config.options` with a custom `AttributeDict`. I didn't know `config` now contains an `options` element when it is initialized. If I don't override `config.options` , then it works as expected (i.e., I get a warning that `asdf_path` should be a list).
However, I noticed that `config.clear()` does not reset `config.options`. Is that intended?

**Comment by claudiodsf** [comment]
> However, I noticed that `config.clear()` does not reset `config.options`. Is that intended?

No, I'll fix that :wink:

**Comment by claudiodsf** [comment]
I just pushed a new commit which moves reading of station metadata from SAC header to `read_traces()` and `read_station_metadata()` instead of `augment_traces()`.

This is a step forward in making `augment_traces()` format independent and usable with any stream read by ObsPy.

These changes should not impact your workflow, but if you want to make a test, you're welcome 😉

**Comment by krisvanneste** [comment]
> These changes should not impact your workflow, but if you want to make a test, you're welcome 😉

I don't notice any difference.

**Comment by claudiodsf** [comment]
> > However, I noticed that `config.clear()` does not reset `config.options`. Is that intended?
> 
> No, I'll fix that 😉

Should be fixed now!

**Comment by krisvanneste** [comment]
> > > However, I noticed that `config.clear()` does not reset `config.options`. Is that intended?
> > 
> > 
> > No, I'll fix that 😉
> 
> Should be fixed now!

Indeed!

**Comment by claudiodsf** [comment]
> I was thinking about moving trace selection based on the configuration (config.use_traceids, config.ignore_traceids) from augment_traces() to read_traces(). This is currently implemented in the function [ _select_components(st)](https://github.com/SeismicSource/sourcespec/blob/7730346bcbc577eaa35acb0a2fe7fdcb6e379b3b/sourcespec2/input/augment_traces.py#L68).

I made this change in the latest commit. Easy to revert, if you do not agree.

**Comment by krisvanneste** [comment]
> > I was thinking about moving trace selection based on the configuration (config.use_traceids, config.ignore_traceids) from augment_traces() to read_traces(). This is currently implemented in the function [ _select_components(st)](https://github.com/SeismicSource/sourcespec/blob/7730346bcbc577eaa35acb0a2fe7fdcb6e379b3b/sourcespec2/input/augment_traces.py#L68).
> 
> I made this change in the latest commit. Easy to revert, if you do not agree.

I will have a look at the modification.

**Comment by krisvanneste** [comment]
> > > I was thinking about moving trace selection based on the configuration (config.use_traceids, config.ignore_traceids) from augment_traces() to read_traces(). This is currently implemented in the function [ _select_components(st)](https://github.com/SeismicSource/sourcespec/blob/7730346bcbc577eaa35acb0a2fe7fdcb6e379b3b/sourcespec2/input/augment_traces.py#L68).
> > 
> > 
> > I made this change in the latest commit. Easy to revert, if you do not agree.
> 
> I will have a look at the modification.

Claudio, I can follow your logic. If the user bypasses sourcespec's input functions, [s]he is responsible for building the stream and if necessary can run `_select_components()` manually. However, it may not be so easy for a user to see which configuration parameters are going to be applied in a given situation. I was wondering if it would be possible to reflect that somehow in configuration categories (maybe similar to the new submodules), e.g. `config.input.*`, `config.preprocessing.*`, `config.processing.*`, `config.output.*`, ... ? Or is this too far-fetched?

Concerning the current `config.options` category (which may disappear in the near future), shouldn't this be populated with the required parameters when initialized? I just ran into a problem when running `ssp_run` if I don't explicitly set `config.options.outdir` and `config.options.evname`.

**Comment by krisvanneste** [comment]
> Ok, I'll let you do this, since I don't have the use case at hand.

I will give it a try today.

**Comment by claudiodsf** [comment]
> Claudio, I can follow your logic. If the user bypasses sourcespec's input functions, [s]he is responsible for building the stream and if necessary can run `_select_components()` manually. However, it may not be so easy for a user to see which configuration parameters are going to be applied in a given situation. I was wondering if it would be possible to reflect that somehow in configuration categories (maybe similar to the new submodules), e.g. `config.input.*`, `config.preprocessing.*`, `config.processing.*`, `config.output.*`, ... ? Or is this too far-fetched?

That's an interesting idea. It should be doable using [sections](https://configobj.readthedocs.io/en/latest/configobj.html#sections) in ConfigObj.
I'm going to take note of this in #53.


> Concerning the current `config.options` category (which may disappear in the near future), shouldn't this be populated with the required parameters when initialized? I just ran into a problem when running `ssp_run` if I don't explicitly set `config.options.outdir` and `config.options.evname`.

I was working on this right now! It should be fixed with the latest commit, can you check?

Also, commit https://github.com/SeismicSource/sourcespec/pull/56/commits/db8a1ecd5e809d01243e890569a94394e379c8c0 modifies `ssp_exit()` so that it raises an exception, instead of calling `sys.exit()`, when running from API.

**Comment by claudiodsf** [comment]
> > Concerning the current `config.options` category (which may disappear in the near future), shouldn't this be populated with the required parameters when initialized? I just ran into a problem when running `ssp_run` if I don't explicitly set `config.options.outdir` and `config.options.evname`.
> 
> I was working on this right now! It should be fixed with the latest commit, can you check?

I used a different approach, via `getattr(config.options, OPT, None)`, whenever `OPT` is needed. I could run a modified version of your notebook where `config.options` is uninitialized, but I maybe ignore some other corner cases 😉

**Comment by krisvanneste** [comment]
> > > Concerning the current `config.options` category (which may disappear in the near future), shouldn't this be populated with the required parameters when initialized? I just ran into a problem when running `ssp_run` if I don't explicitly set `config.options.outdir` and `config.options.evname`.
> > 
> > 
> > I was working on this right now! It should be fixed with the latest commit, can you check?
> 
> I used a different approach, via `getattr(config.options, OPT, None)`, whenever `OPT` is needed. I could run a modified version of your notebook where `config.options` is uninitialized, but I maybe ignore some other corner cases 😉

OK, I see. I checked and it works without having `config.options.outdir` and `config.options.evname`. By the way, wasn't the latter parameter supposed to be set when reading event data?

**Comment by claudiodsf** [comment]
> OK, I see. I checked and it works without having `config.options.outdir` and `config.options.evname`. 

Great!

> By the way, wasn't the latter parameter supposed to be set when reading event data?

I admit, I'm lost. But I think that `evname` is retrieved throughout the code from the `Event` object.

Anyway, `config.options` is not going to stay!

**Comment by claudiodsf** [comment]
We can maybe merge this PR now?

**Comment by krisvanneste** [comment]
> We can maybe merge this PR now?

Can I still try adding support for wildcards in ASDF tags? I will look into it now.

**Comment by claudiodsf** [comment]
> > We can maybe merge this PR now?
> 
> Can I still try adding support for wildcards in ASDF tags? I will look into it now.

Sure!

**Comment by krisvanneste** [comment]
I added support for wildcards ('?' or '*') in ASDF tags.
With an ASDF file downloaded from ESM, I can now set
```
config.options.asdf_tag = '00_hg?_emsc_20160824_0000006_dis_mp'
```
to read 3 traces (including trace headers), even though they are stored with different tags.
Note that I also added a `header_key` argument to `_parse_asdf_headers()` replacing the hardcoded "TraceHeaders".
This will allow us to write a notebook using data downloaded from ESM (if we find the time)...

**Comment by claudiodsf** [comment]
> I added support for wildcards ('?' or '*') in ASDF tags. With an ASDF file downloaded from ESM, I can now set
> 
> ```
> config.options.asdf_tag = '00_hg?_emsc_20160824_0000006_dis_mp'
> ```
> 
> to read 3 traces (including trace headers), even though they are stored with different tags. Note that I also added a `header_key` argument to `_parse_asdf_headers()` replacing the hardcoded "TraceHeaders". This will allow us to write a notebook using data downloaded from ESM (if we find the time)...

Great! Saw that!

The only thing missing, from my point of view, is command line support for multiple tags (i.e., `-g/--tag` option should take multiple arguments).
I can do that! 😉

**Comment by claudiodsf** [comment]
Wait! This is not even supported from your code: the `tag` argument in `parse_asdf_traces()` is always just a string.
It can become a list later in `_parse_asdf_trace_headers()`.

So, the use cases are:
- a simple tag, e.g. `tag`
- a tag with wildcards, e.g. `tag*` or `tag??`
- no explicit list of tags, e.g. `['aaaa', 'bbbb', 'cccc']`

If that is fine with you, there is nothing to change!

Alternatively, we could allow the latter by splitting tag by comma, e.g.:

```python
config.options.asdf_tag = 'aaaa,bbbb,cccc'
```

What do you think?
```

**Comment by claudiodsf** [comment]
> * We could support different ASDF tags for different ASDF files, but this should be handled in `input.traces._read_asdf_traces()`, which then dispatches the correct tag to `parse_asdf_traces()`. This could be done using a simple list, no need to embed commas in a string.

Is this a plausible use case?
If yes, could you please go ahead and implement it?

Thanks!

**Comment by krisvanneste** [comment]
> > * We could support different ASDF tags for different ASDF files, but this should be handled in `input.traces._read_asdf_traces()`, which then dispatches the correct tag to `parse_asdf_traces()`. This could be done using a simple list, no need to embed commas in a string.
> 
> Is this a plausible use case? If yes, could you please go ahead and implement it?
> 
> Thanks!

Not very likely, but possible. I will implement it in `input.traces._read_asdf_traces()`.

**Comment by krisvanneste** [comment]
Done. I have no test case but at least the case with 1 tag still works...

**Comment by claudiodsf** [comment]
Great, thanks!

I'll make my test, then some cosmetic changes (if necessary), then merge!

**Comment by claudiodsf** [comment]
Ok, I pushed some small changes.

Should `trace_tags` be renamed to `waveform_tags` for consistency?

**Comment by krisvanneste** [comment]
> Ok, I pushed some small changes.
> 
> Should `trace_tags` be renamed to `waveform_tags` for consistency?

Do you mean in `_parse_asdf_trace_headers()`?

**Comment by claudiodsf** [comment]
> > Ok, I pushed some small changes.
> > Should `trace_tags` be renamed to `waveform_tags` for consistency?
> 
> Do you mean in `_parse_asdf_trace_headers()`?

Yes, but also in `parse_asdf_traces()`

**Comment by krisvanneste** [comment]
OK, I see.
I think so, yes. From there on, if `trace_tags` is a list, it really refers to the tags of each individual trace.

**Comment by claudiodsf** [comment]
> OK, I see. I think so, yes. From there on, if `trace_tags` is a list, it really refers to the tags of each individual trace.

So we keep it to `trace_tags`?

**Comment by krisvanneste** [comment]
> > OK, I see. I think so, yes. From there on, if `trace_tags` is a list, it really refers to the tags of each individual trace.
> 
> So we keep it to `trace_tags`?

Yes, but maybe update the docstring to "trace tag(s) in ASDF file"?
I will be away ~1 hour for lunch...

**Comment by claudiodsf** [comment]
Done! Let me know if you're happy with that and I'll merge!

Bon appetit!

**Comment by krisvanneste** [comment]
> Done! Let me know if you're happy with that and I'll merge!
> 
> Bon appetit!

Looks good to me!

**Comment by claudiodsf** [comment]
Time to hit that "Merge" button!

Thanks for this good work! 🙏

**Comment by claudiodsf** [comment]
I will not have time to further work on SourceSpec today.
I'll try to do some further work tomorrow (last day before vacation).

**Comment by krisvanneste** [comment]
Thank you too, Claudio.
What will you be working on tomorrow? Let me know if I can do something.

**Pull request merged**
