### PR TITLE
Use `trace.remove_response()` for instrument correction

### PR DESCRIPTION
**Pull request by claudiodsf**
This PR modernizes the instrument correction routine `remove_instr_response()` which goes from using `trace.simulate()` and poles and zeros to `trace.remove_response()` and full response, as defined in the `Inventory()` object.

In case users provide a PAZ file, this is converted to an `Inventory()` object using a custom routine.

Tested and validated on all my examples.

@krisvanneste, I don't know if you use instrument correction from SourceSpec. If that's the case, I'll wait on your feedback before merging. Thanks!

### CODE REVIEW

**Comment by krisvanneste** [comment]
Claudio,

I will try it.
Kris

**Comment by krisvanneste** [comment]
Unfortunately, I have a problem with my obspy version. I'm still on 1.2.2, but now 1.3.0 is required.
Do you use some specific functionality in 1.3.0 that was not there in 1.2.2?
It would of course be good if I update obspy, but I tried it before and the conda updater never found a solution to sort out the dependencies. I will try to clone my environment and try forcing the update...

**Comment by claudiodsf** [comment]
The reason why I moved to ObsPy 1.3.0 is the option `'DEF'` in `trace.remove_response()` ([this line](https://github.com/SeismicSource/sourcespec/blob/5bea7ea123af047d3699c4df471af297a8cba2ca/sourcespec/ssp_util.py#L236)), so that I convert the trace to its nominal units (before doing the integration in `ssp_build_spectra()`).

A workaround could be to retrieve nominal units from `inv.get_response(trace.id, trace.stats.starttime).instrument_sensitivity.input_units` and set output to `'VEL'`, `'DISP'` or `'ACC'` accordingly.

I can do that! ;-)

**Comment by krisvanneste** [comment]
Thanks for the quick fix!
It runs now.
Now I get the following error message for all stations:
`BE.BEBN..HHZ broadb: Unable to remove instrument response: skipping trace`
However, this may be due to the way I run sourcespec. I will investigate.

**Comment by krisvanneste** [comment]
I finally fixed it. Instead of `_add_paz_and_coords`, I had to call `_add_inventory`, `_add_coords` and `_check_instrtype`. I also had to turn off clipping detection if I pre-restitute my traces before running sourcespec.
For the example I used, I obtain moment magnitudes that differ less than 0.1 (with 1 exception). The differences can best be evaluated based on the spectra.
Spectra obtained after restitution inside sourcespec:
3069 ssp 00
Spectra obtained after pre-restitution to displacement:
3069 ssp 00

The largest difference can be observed for station BE.UCCS. I think this is due to more narrow pre-filtering on my side.

**Comment by krisvanneste** [comment]
The example also reminds me that I should ask you if it is possible to constrain `Qo` to positive values...

**Comment by claudiodsf** [comment]
> For the example I used, I obtain moment magnitudes that differ less than 0.1 (with 1 exception). The differences can best be evaluated based on the spectra.

What's your metadata format? StationXML, datalessSEED, PAZ, other?

**Comment by krisvanneste** [comment]
Thanks for the pointer!

**Comment by krisvanneste** [comment]
> > For the example I used, I obtain moment magnitudes that differ less than 0.1 (with 1 exception). The differences can best be evaluated based on the spectra.
> 
> What's your metadata format? StationXML, datalessSEED, PAZ, other?

It's StationXML in this case; in other cases it may also be dataless SEED.

**Comment by claudiodsf** [comment]
> It's StationXML in this case; in other cases it may also be dataless SEED.

Ok, thanks.

Do you think we can validate this, or do you prefer to do more testing?

**Comment by krisvanneste** [comment]
I don't think I can test more from my side. I always work with full obspy station inventories, not with PAZ.

**Comment by claudiodsf** [comment]
Ok, thanks. So, I'm going to merge this and wait for bug reports ::😜

**Comment by krisvanneste** [comment]
OK!

**Pull request merged**
