### PR TITLE
V2 qml improvements

### PR DESCRIPTION
**Pull request by krisvanneste**
Claudio, I made some modifications in `input.event_metadata.py`  which will be more handy to parse QML from other sources (e.g. ASDF files, obspy Event):
- Renamed `_get_event_from_qml` function to `_get_event_from_qml_cat`
- Moved code from `parse_qml` function to new `parse_qml_event` function
- Added new `parse_asdf` function

### CODE REVIEW

**Comment by claudiodsf** [comment]
Thanks Kris!

Looks like there is a rebase problem (too many commits). I'll take care of that and force-push, before reviewing your changes.

**Comment by krisvanneste** [comment]
OK, I hope I didn't do something wrong.

**Comment by krisvanneste** [comment]
Claudio, I think the problem is that I did the pull request into `main` rather than `v2`. If you discard this one, I can do the request again in the right branch...

**Comment by claudiodsf** [comment]
Yes, the problem is indeed the wrong target branch. Fixed!

**Comment by krisvanneste** [comment]
Great, I didn't know that was possible. Thanks!

**Comment by claudiodsf** [comment]
Hello, I just pushed a commit where I further split the event parsers into different files.
Hopefully, that will make the code easier to maintain and extend in the future.

You should still be able to read ASDF with something like:

```python
from sourcespec2.input.event_parsers import parse_asdf_file
event, picks = parse_asdf_file(asdf_file)
```

I also added a check when importing `pyasdf`, since I don't want it to be a hard dependency 😉 .

Let me know if you're ok with these modifications.

**Comment by claudiodsf** [comment]
Force-pushed again with common code between `ASDF` and `QuakeML` moved to `obspy_catalog.py`.
Good for me now.

**Comment by krisvanneste** [comment]
I wanted to test, but I'm having a problem with github again:
```
git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks fetch --no-tags github
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:uNiVztksCsDhcc0u9e8BujQXVUpKZIDTMczCvj3tD2s.
Please contact your system administrator.
Add correct host key in /c/Users/kris/.ssh/known_hosts to get rid of this message.
Offending RSA key in /c/Users/kris/.ssh/known_hosts:1
Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.
```
I will need to solve that first.

**Comment by krisvanneste** [comment]
Maybe one more suggestion: as ASDF files contain different sorts of information, it would be better to rename the function `parse_asdf_file` to something like `parse_qml_from_asdf_file` or `parse_asdf_file_qml`.

**Comment by claudiodsf** [comment]
> Maybe one more suggestion: as ASDF files contain different sorts of information, it would be better to rename the function `parse_asdf_file` to something like `parse_qml_from_asdf_file` or `parse_asdf_file_qml`.

True! Renamed to `parse_asdf_event_picks()` and force-pushed.

**Comment by claudiodsf** [comment]
> I wanted to test, but I'm having a problem with github again:

This seems related to the GitHub RSA SSH host key change they made in March 2023: https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/

Strange that it shows up now 🤔

**Comment by krisvanneste** [comment]
I tested both `parse_obspy_catalog` and `parse_asdf_event_picks` and they work.
I had to set `config.config.qml_event_description = True` to get the event name, but I suppose this is how it works.

**Comment by claudiodsf** [comment]
> I had to set `config.config.qml_event_description = True` to get the event name, but I suppose this is how it works.

Yes, it works like this right now. We might change this in the future, but for the moment I'm going to merge this.

I'm going to focus now on refactoring the processing function into a `processing` submodule 😉

**Comment by krisvanneste** [comment]
> Yes, it works like this right now. We might change this in the future, but for the moment I'm going to merge this.
> 
> I'm going to focus now on refactoring the processing function into a `processing` submodule 😉

OK, I have a suggestion related to attaching instrument response, but I will wait for your refactoring first!

**Comment by claudiodsf** [comment]
> OK, I have a suggestion related to attaching instrument response, but I will wait for your refactoring first!

Please let me know! I will not work on the refactoring until later this morning or in the afternoon.

By the way, I just pushed two commits to fix the regression with SAC files, where metadata and event info is in the sac header.

**Comment by krisvanneste** [comment]
> Please let me know! I will not work on the refactoring until later this morning or in the afternoon.

It is related to my suggestion to allow `inventory` to be empty in case response is already attached to the traces in `st`. I noticed that you attach an Inventory object to the trace headers, while the standard way in `obspy.Trace.attach_response` is to only attach the channel response. My suggestion is to see if it is possible to do the same as obspy without breaking anything further downstream. This would make it easier to test if response is already attached or not. Is there a particular reason for attaching an Inventory object rather than a Response object to the trace headers?

Another suggestion is to move the signal analysis functions (including `remove_instr_response()`) to this new `processing` submodule.

I would also like to add functions to read inventories and traces from ASDF files, but that's in the `input` submodule. I can prepare a pull request for this.

**Comment by krisvanneste** [comment]
> I could not find anything in the ObsPy doc, except [this series of examples](https://docs.obspy.org/tutorial/advanced_exercise/advanced_exercise_solution_5.html), where they store coordinates into `tr.stats.coordinates`, so I'll probably stick with that.

Nice catch!

**Pull request merged**
