### PR TITLE
sql_output_outlier

### PR DESCRIPTION
**Pull request by krisvanneste**
Patch to include information about outliers for each parameter in the Stations table in the SQL output.

### CODE REVIEW

**Comment by claudiodsf** [comment]
Ok for me (after adding the outlier information also for the radiated energy 😉).

Note that I had to increment `DB_VERSION` since the database schema has changed.

I profited of this change to reorder the fields, so that radiated energy is before distance and azimuth.

Ok to merge after a double-check on your side 👍

**Comment by krisvanneste** [comment]
Works for me.

**Comment by claudiodsf** [comment]
Rebased and force-pushed.
@krisvanneste, could you double-check?

P.S. I will profit of the DB_VERSION change to make other modifications in the DB, directly on the `main` branch, after this PR is merged.

**Comment by claudiodsf** [comment]
Ok, merging!

**Comment by claudiodsf** [comment]
I pushed 44c5d2d with more DB modifications.

Hopefully, it doesn't break anything 😉

**Comment by krisvanneste** [comment]
Nice bit of refactoring!

**Comment by claudiodsf** [comment]
> Nice bit of refactoring!

Thanks to Copilot and Sourcery 😉

**Pull request merged**
